### ISSUE TITLE
Loose URLs

### ISSUE THREAD

**Issue by EricPHassey** [Cretezy/linkify#1]
www.yahoo.com isn't found as a link, only http://www.yahoo.com. Anything that has www before it should be considered a link, IMO.

**Comment by Cretezy** [comment]
I have moved this issue to the new package for the underlying library for parsing

**Comment by sjmcdowall** [comment]
How goes the loose option?  One of our customers just asked for it... I'm not a RE guru and the current one already looks intimidating .. ;)

**Comment by Cretezy** [comment]
I'm going to look into it this weekend, hopefully I'll come up with something nice! I'll keep my updates posted here.

**Comment by andrewmatte** [comment]
https://github.com/Cretezy/linkify/pull/7

Hi! Can you please take a look at this to see what you think?

**Comment by kazenokage** [comment]
Any progress on this? I'm about to use the plugin to parse user-created text, but our users rarely type the `https://` before the actual url (and I really can't blame them). One easy way out of this might be adding an option for custom regex and just setting the current one as default. This way one could use regex that suits the need at hand better.

**Comment by Cretezy** [comment]
This has been added with v2.1.0.

**Comment by Thandohimself** [comment]
@Cretezy  How do I support www.google.com and also be able to Select and Copy text...right now

if I use SelectableLinkify
1. I can not open www.google.com 
2. I can select and copy text 

If I use Linkify 
1. I can open www.google.com
2 I can not select and copy text

**Comment by Cretezy** [comment]
Update Flutter. This is a Flutter bug recently fixed. It makes SelectableText unclickable.

**Comment by Thandohimself** [comment]
@Cretezy  I did still not working on my side, this is my `flutter doctor` 

[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.3 19D76, locale en-ZA)
    • Flutter version 1.17.0 at /Users/macbookair/flutter
    • Framework revision e6b34c2b5c (10 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/macbookair/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Comment by Cretezy** [comment]
Can you try the `beta` or `dev` branches (the fix in in 1.18)? Either way, this is a problem for https://github.com/Cretezy/flutter_linkify, not this library.

We had an issue with this tracked: https://github.com/Cretezy/flutter_linkify/issues/31
