### ISSUE TITLE
Humanize should also remove www

### ISSUE THREAD

**Issue by adrianvintu** [Cretezy/linkify#16]
In my chat app, the `www` looks like extra information no one cares about - and also looks very ugly.

For this link https://www.youtube.com/watch?v=q6MF3OIhW8I `humanize` removes the `https://` part.

Can you please
A make `humanize` remove `www`
or
B. add a new option to remove `www`
or
C. make `humanize` an enum {RemoveHTTP, RemoveWWW}
?

The visual result would be [youtube.com/watch?v=q6MF3OIhW8I](url)

Thank you for your great work!

**Comment by Cretezy** [comment]
This has been added with v2.1.0.
