### ISSUE TITLE
Support for phone number

### ISSUE THREAD

**Issue by mannprerak2** [Cretezy/linkify#2]
Add support for phone numbers so they could be opened easily

**Comment by Cretezy** [comment]
I have moved this issue to the new package for the underlying library for parsing

**Comment by mannprerak2** [comment]
Can you provide me a link to that?

**Comment by Cretezy** [comment]
@mannprerak2 this is the moved one, it's the same issue, different repo!

**Comment by mannprerak2** [comment]
Hey i added a PR, please review it

**Comment by yongjhih** [comment]
Detect `tel://` for `UrlLauncher.launch("tel://21213123123")`

**Comment by Cretezy** [comment]
Hi, this is now possble using custom linkifiers. Please see the new README for v2.0.0.
