### ISSUE TITLE
Not able to detect Multiple URL.

### ISSUE THREAD

**Issue by iavsm** [Cretezy/linkify#22]
I am trying two display two URLs with the below code but it's detecting only the first one.
This is how it's displaying in the application.

![Screenshot 2020-06-09 at 5 20 22 PM](https://user-images.githubusercontent.com/6705574/84144212-82c3ff80-aa75-11ea-83fe-1f16f85a2306.png)

``` Dart
Linkify(
          onOpen: (link) async => {
            if (await canLaunch(link.url))
              {
                await launch(link.url),
              }
            else
              {
                throw 'Could not launch $link',
              }
          },
          text: message,
          style: TextStyle(
            color: color,
            fontSize: fontSize,
            fontWeight: fontWeight,
            fontFamily: Fonts.TITLE,
          ),
          options: LinkifyOptions(humanize: false),
        ),
```

flutter_linkify: ^3.1.3   

[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.14.5 18F132, locale en-IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.45.1)
[✓] Connected device (1 available)

**Comment by Cretezy** [comment]
This should have been fixed in v3.0.0. Please try again!

Feel free to reopen
