### ISSUE TITLE
Could not able to find the linkify without https://

### ISSUE THREAD

**Issue by SureShDood** [Cretezy/linkify#23]
example : 
 facebook.com
 www.google.com

used loose, http://facebook.com considered url. 

if i used loose, all dots (.) consider that url. 
example. http://1.  or something. also considered url.

Please fix it asap.

**Comment by vashisth00** [comment]
Please can you update on this

**Comment by Cretezy** [comment]
This seems to be expected behavior.

`facebook.com` is **not** a valid URL. Using loose URLs will fix this.

Support for non-loose `www.` URLs has been recently added
