### ISSUE TITLE
Could not able to identify the valid url

### ISSUE THREAD

**Issue by SureShDood** [Cretezy/linkify#24]
I have tried to without https://, Could not able to get the valid url. 

Example. I try to give www.facebook.com , facebook.com
it's not recognised the valid url.  i given the looseUrl option true. 
All dots (.) considered the url format.

**Comment by Cretezy** [comment]
Took a deeper look at this.

`www.facebook.com` is **not** a valid URL. Only `https://www.facebook.com` is. It seems the library is acting correctly.

Parsing of `www.` URLs without loose URLs enable has been added recently though.

The dots will be addressed inside https://github.com/Cretezy/linkify/issues/25
